# Generated by Django 2.2.17 on 2020-12-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201212_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_desc',
            field=models.CharField(max_length=32, verbose_name='short desc'),
        ),
    ]
